// -------User define function----------------

                
                  # declare function
                def myf(str):
                  # str=print("Welcome to python...")
                  print(str)
                  
                print("my first python function..")
                   
                  # call myf function
                myf("Welcome")
        
        
                  Output:
                  my first python function..
                  Welcome

               // -------------------------------------------
                
                  # User define function
                  # declare function
                def myf(str,str1):
                  # str=print("Welcome to python...")
                  print(str,str1)
                  
                print("my first python function..")
                   
                  # call myf function
                myf("Welcome","python")
                
                Output:
                
                my first python function..
                Welcome python

// ------------------------------------------
